clone:
        depth: 10
        recursive: true

build:
        image: ubuntu-initial
        commands:
                - mkdir /root/.ssh
                - cd  /root/.ssh
                - touch id_rsa
                - touch test
                - echo $$SSH_K > /root/.ssh/id_rsa
                - cat /root/.ssh/id_rsa
                - chmod 400 /root/.ssh/id_rsa
                - echo $GOPATH && export PATH=$PATH:$GOROOT/bin:$GOPATH/bin && echo $GOPATH &&
                  scp -vvv -o StrictHostKeyChecking=no -P 22  -o PasswordAuthentication=no -o BatchMode=yes $GOPATH/src/github.com/KristinaEtc/go-nominatim/go-deb/*.deb k@192.168.240.60:~/
        when:
                branch: [master,dev,release,deploy]

