clone:
        depth: 10
        recursive: true

build:
                image: golang:1.6.1
                environment:
                        - GOOS=linux
                        - GOARCH=amd64
                        - CGO_ENABLED=0
                commands:
                        - docker build -t nominatim .
                branches:
                        - release
                        - master
                        - dev
                        - deploy
