clone:
        depth: 50
        recursive: true

build:
                image: golang:1.6.1
                environment:
                        - GOOS=linux
                        - GOARCH=amd64
                        - CGO_ENABLED=0
                commands:
                        - go get github.com/kardianos/govendor
                        - govendor sync
                        - go build
                        - time 10s ./go-nominatim
                branches:
                        - release
                        - master
                        - dev
                        - deploy
