clone:
        depth: 10
        recursive: true

build:
        image: go-nominatim
                commands:
                        - go env

                branches:
                        - release
                        - master
                        - dev
                        - deploy

