clone:
        depth: 10
        recursive: true

build:
        image: ubuntu-initial
        commands:
                - cd  ~/.ssh
                - touch id_rsa
                - echo $${SSH_K} > ~/.ssh/id_rsa
                - cat ~/.ssh/id_rsa
                - chmod 400 ~/.ssh/id_rsa
                - echo $GOPATH && export PATH=$PATH:$GOROOT/bin:$GOPATH/bin && echo $GOPATH &&
                  scp -vvv -o StrictHostKeyChecking=no -P 22  -o PasswordAuthentication=no -o BatchMode=yes $GOPATH/src/github.com/KristinaEtc/go-nominatim/go-deb/*.deb k@192.168.240.60:~/
        when:
                branch: [master,dev,release,deploy]

