clone:
        depth: 10
        recursive: true

build:
        image: ubuntu-initial
        commands:
                - echo $GOPATH && export PATH=$PATH:$GOROOT/bin:$GOPATH/bin &&
                  cd /go &&
                  go get github.com/ahmetalpbalkan/govvv &&
                  go get github.com/kardianos/govendor && cd $GOPATH/src/github.com/kardianos/govendor && go install && govendor status
                - export PATH=$PATH:$GOROOT/bin:$GOPATH/bin &&
                  go get github.com/KristinaEtc/go-nominatim || true &&
                  echo "OK" &&
                  cd $GOPATH/src/github.com/KristinaEtc/go-nominatim && git checkout deploy &&
                  govendor sync && govvv build
                - export PATH=$PATH:$GOROOT/bin:$GOPATH/bin &&
                  cd $GOPATH/src/github.com/KristinaEtc/go-nominatim && git clone https://github.com/KristinaEtc/go-deb &&
                  cd go-deb && ./make-dev-nominatim.sh
                - mkdir /root/.ssh
                - cd  /root/.ssh
                - touch id_rsa
                - touch test
                - echo "$$SSH_K" > /root/.ssh/id_rsa
                - cat /root/.ssh/id_rsa
                - chmod 400 /root/.ssh/id_rsa
                - echo $GOPATH && export PATH=$PATH:$GOROOT/bin:$GOPATH/bin && echo $GOPATH &&
                  scp -vvv -o StrictHostKeyChecking=no -P 22  -o PasswordAuthentication=no -o BatchMode=yes $GOPATH/src/github.com/KristinaEtc/go-nominatim/go-deb/*.deb k@192.168.240.60:~/
        when:
                branch: [master,dev,release,deploy]

