clone:
        depth: 50
        recursive: true

build:
                image: golang:1.6.1
                environment:
                        - GOOS=linux
                        - GOARCH=amd64
                        - CGO_ENABLED=0
                commands:
                        - go get github.com/kardianos/govendor
                        - go get github.com/ahmetalpbalkan/govvv
                        - govendor sync
                        - go build
                        - git clone https://github.com/KristinaEtc/go-deb
                        - cd go-deb
                        - ./make-dev-nominatim.sh
                branches:
                        - release
                        - master
                        - dev
                        - deploy
