clone:
        depth: 10
        recursive: true

build:
        image: go-nominatim
                environment:
                        - GOOS=linux
                        - GOARCH=amd64
                        - CGO_ENABLED=0
                commands:
                        - go env

                branches:
                        - release
                        - master
                        - dev
                        - deploy

