clone:
        depth: 10
        recursive: true

build:
        image: ubuntu-initial
        commands:
                - echo $GOPATH && export PATH=$PATH:$GOROOT/bin:$GOPATH/bin &&
                  cd /go &&
                  go get github.com/ahmetalpbalkan/govvv &&
                  go get github.com/kardianos/govendor && cd $GOPATH/src/github.com/kardianos/govendor && go install && govendor status
                - export PATH=$PATH:$GOROOT/bin:$GOPATH/bin &&
                  go get github.com/KristinaEtc/go-nominatim || true &&
                  echo "OK" &&
                  cd $GOPATH/src/github.com/KristinaEtc/go-nominatim && git checkout deploy &&
                  govendor sync && govvv build
                - export PATH=$PATH:$GOROOT/bin:$GOPATH/bin &&
                  cd $GOPATH/src/github.com/KristinaEtc/go-nominatim && git clone https://github.com/KristinaEtc/go-deb &&
                  cd go-deb && ./make-dev-nominatim.sh

deploy:
        bash:
                script:
                        - scp -o StrictHostKeyChecking=no -P 22 -r . deploy@178.62.79.10:app-build/
                when:
                        branch: master,dev,release,deploy

