FROM ubuntu
MAINTAINER Kristina Etc

RUN apt-get update -qq &&  apt-get install -y checkinstall && \
apt-get install -y curl && apt-get install -yq golang && \
apt-get install -yq git

# Set up GOPATH
RUN mkdir /go
ENV GOPATH /go
