package Nominatim

func getClassTypes() (m map[string]map[string]string) {
	m = map[string]map[string]string{

		"boundary:administrative:1":    {"label": "Continent", "frequency": "0", "icon": "poi_boundary_administrative", "defdiameter": "0.32"},
		"boundary:administrative:2":    {"label": "Country", "frequency": "0", "icon": "poi_boundary_administrative", "defdiameter": "0.32"},
		"place:country":                {"label": "Country", "frequency": "0", "icon": "poi_boundary_administrative", "defzoom": "6", "defdiameter": "15"},
		"boundary:administrative:3":    {"label": "State", "frequency": "0", "icon": "poi_boundary_administrative", "defdiameter": "0.32"},
		"boundary:administrative:4":    {"label": "State", "frequency": "0", "icon": "poi_boundary_administrative", "defdiameter": "0.32"},
		"place:state":                  {"label": "State", "frequency": "0", "icon": "poi_boundary_administrative", "defzoom": "8", "defdiameter": "5.12"},
		"boundary:administrative:5":    {"label": "State District", "frequency": "0", "icon": "poi_boundary_administrative", "defdiameter": "0.32"},
		"boundary:administrative:6":    {"label": "County", "frequency": "0", "icon": "poi_boundary_administrative", "defdiameter": "0.32"},
		"boundary:administrative:7":    {"label": "County", "frequency": "0", "icon": "poi_boundary_administrative", "defdiameter": "0.32"},
		"place:county":                 {"label": "County", "frequency": "108", "icon": "poi_boundary_administrative", "defzoom": "10", "defdiameter": "1.28"},
		"boundary:administrative:8":    {"label": "City", "frequency": "0", "icon": "poi_boundary_administrative", "defdiameter": "0.32"},
		"place:city":                   {"label": "City", "frequency": "66", "icon": "poi_place_city", "defzoom": "12", "defdiameter": "0.32"},
		"boundary:administrative:9":    {"label": "City District", "frequency": "0", "icon": "poi_boundary_administrative", "defdiameter": "0.32"},
		"boundary:administrative:10":   {"label": "Suburb", "frequency": "0", "icon": "poi_boundary_administrative", "defdiameter": "0.32"},
		"boundary:administrative:11":   {"label": "Neighbourhood", "frequency": "0", "icon": "poi_boundary_administrative", "defdiameter": "0.32"},
		"place:region":                 {"label": "Region", "frequency": "0", "icon": "poi_boundary_administrative", "defzoom": "8", "defdiameter": "0.04"},
		"place:island":                 {"label": "Island", "frequency": "288", "icon": "", "defzoom": "11", "defdiameter": "0.64"},
		"boundary:administrative":      {"label": "Administrative", "frequency": "413", "icon": "poi_boundary_administrative", "defdiameter": "0.32"},
		"boundary:postal_code":         {"label": "Postcode", "frequency": "413", "icon": "poi_boundary_administrative", "defdiameter": "0.32"},
		"place:town":                   {"label": "Town", "frequency": "1497", "icon": "poi_place_town", "defzoom": "14", "defdiameter": "0.08"},
		"place:village":                {"label": "Village", "frequency": "11230", "icon": "poi_place_village", "defzoom": "15", "defdiameter": "0.04"},
		"place:hamlet":                 {"label": "Hamlet", "frequency": "7075", "icon": "poi_place_village", "defzoom": "15", "defdiameter": "0.04"},
		"place:suburb":                 {"label": "Suburb", "frequency": "2528", "icon": "poi_place_village", "defdiameter": "0.04"},
		"place:locality":               {"label": "Locality", "frequency": "4113", "icon": "poi_place_village", "defdiameter": "0.02"},
		"landuse:farm":                 {"label": "Farm", "frequency": "1201", "icon": "", "defdiameter": "0.02"},
		"place:farm":                   {"label": "Farm", "frequency": "1162", "icon": "", "defdiameter": "0.02"},
		"highway:motorway_junction":    {"label": "Motorway Junction", "frequency": "1126", "icon": "", "simplelabel": "Road"},
		"highway:motorway":             {"label": "Motorway", "frequency": "4627", "icon": "", "simplelabel": "Road"},
		"highway:trunk":                {"label": "Trunk", "frequency": "23084", "icon": "", "simplelabel": "Road"},
		"highway:primary":              {"label": "Primary", "frequency": "32138", "icon": "", "simplelabel": "Road"},
		"highway:secondary":            {"label": "Secondary", "frequency": "25807", "icon": "", "simplelabel": "Road"},
		"highway:tertiary":             {"label": "Tertiary", "frequency": "29829", "icon": "", "simplelabel": "Road"},
		"highway:residential":          {"label": "Residential", "frequency": "361498", "icon": "", "simplelabel": "Road"},
		"highway:unclassified":         {"label": "Unclassified", "frequency": "66441", "icon": "", "simplelabel": "Road"},
		"highway:living_street":        {"label": "Living Street", "frequency": "710", "icon": "", "simplelabel": "Road"},
		"highway:service":              {"label": "Service", "frequency": "9963", "icon": "", "simplelabel": "Road"},
		"highway:track":                {"label": "Track", "frequency": "2565", "icon": "", "simplelabel": "Road"},
		"highway:road":                 {"label": "Road", "frequency": "591", "icon": "", "simplelabel": "Road"},
		"highway:byway":                {"label": "Byway", "frequency": "346", "icon": "", "simplelabel": "Road"},
		"highway:bridleway":            {"label": "Bridleway", "frequency": "1556", "icon": ""},
		"highway:cycleway":             {"label": "Cycleway", "frequency": "2419", "icon": ""},
		"highway:pedestrian":           {"label": "Pedestrian", "frequency": "2757", "icon": ""},
		"highway:footway":              {"label": "Footway", "frequency": "15008", "icon": ""},
		"highway:steps":                {"label": "Steps", "frequency": "444", "icon": "", "simplelabel": "Footway"},
		"highway:motorway_link":        {"label": "Motorway Link", "frequency": "795", "icon": "", "simplelabel": "Road"},
		"highway:trunk_link":           {"label": "Trunk Link", "frequency": "1258", "icon": "", "simplelabel": "Road"},
		"highway:primary_link":         {"label": "Primary Link", "frequency": "313", "icon": "", "simplelabel": "Road"},
		"landuse:industrial":           {"label": "Industrial", "frequency": "1062", "icon": ""},
		"landuse:residential":          {"label": "Residential", "frequency": "886", "icon": ""},
		"landuse:retail":               {"label": "Retail", "frequency": "754", "icon": ""},
		"landuse:commercial":           {"label": "Commercial", "frequency": "657", "icon": ""},
		"place:airport":                {"label": "Airport", "frequency": "36", "icon": "transport_airport2", "defdiameter": "0.03"},
		"railway:station":              {"label": "Station", "frequency": "3431", "icon": "transport_train_station2", "defdiameter": "0.01"},
		"amenity:place_of_worship":     {"label": "Place Of Worship", "frequency": "9049", "icon": "place_of_worship_unknown3"},
		"amenity:pub":                  {"label": "Pub", "frequency": "18969", "icon": "food_pub"},
		"amenity:bar":                  {"label": "Bar", "frequency": "164", "icon": "food_bar"},
		"amenity:university":           {"label": "University", "frequency": "607", "icon": "education_university"},
		"tourism:museum":               {"label": "Museum", "frequency": "543", "icon": "tourist_museum"},
		"amenity:arts_centre":          {"label": "Arts Centre", "frequency": "136", "icon": "tourist_art_gallery2"},
		"tourism:zoo":                  {"label": "Zoo", "frequency": "47", "icon": "tourist_zoo"},
		"tourism:theme_park":           {"label": "Theme Park", "frequency": "24", "icon": "poi_point_of_interest"},
		"tourism:attraction":           {"label": "Attraction", "frequency": "1463", "icon": "poi_point_of_interest"},
		"leisure:golf_course":          {"label": "Golf Course", "frequency": "712", "icon": "sport_golf"},
		"historic:castle":              {"label": "Castle", "frequency": "316", "icon": "tourist_castle"},
		"amenity:hospital":             {"label": "Hospital", "frequency": "879", "icon": "health_hospital"},
		"amenity:school":               {"label": "School", "frequency": "8192", "icon": "education_school"},
		"amenity:theatre":              {"label": "Theatre", "frequency": "371", "icon": "tourist_theatre"},
		"amenity:public_building":      {"label": "Public Building", "frequency": "985", "icon": ""},
		"amenity:library":              {"label": "Library", "frequency": "794", "icon": "amenity_library"},
		"amenity:townhall":             {"label": "Townhall", "frequency": "242", "icon": ""},
		"amenity:community_centre":     {"label": "Community Centre", "frequency": "157", "icon": ""},
		"amenity:fire_station":         {"label": "Fire Station", "frequency": "221", "icon": "amenity_firestation3"},
		"amenity:police":               {"label": "Police", "frequency": "334", "icon": "amenity_police2"},
		"amenity:bank":                 {"label": "Bank", "frequency": "1248", "icon": "money_bank2"},
		"amenity:post_office":          {"label": "Post Office", "frequency": "859", "icon": "amenity_post_office"},
		"leisure:park":                 {"label": "Park", "frequency": "2378", "icon": ""},
		"amenity:park":                 {"label": "Park", "frequency": "53", "icon": ""},
		"landuse:park":                 {"label": "Park", "frequency": "50", "icon": ""},
		"landuse:recreation_ground":    {"label": "Recreation Ground", "frequency": "517", "icon": ""},
		"tourism:hotel":                {"label": "Hotel", "frequency": "2150", "icon": "accommodation_hotel2"},
		"tourism:motel":                {"label": "Motel", "frequency": "43", "icon": ""},
		"amenity:cinema":               {"label": "Cinema", "frequency": "277", "icon": "tourist_cinema"},
		"tourism:information":          {"label": "Information", "frequency": "224", "icon": "amenity_information"},
		"tourism:artwork":              {"label": "Artwork", "frequency": "171", "icon": "tourist_art_gallery2"},
		"historic:archaeological_site": {"label": "Archaeological Site", "frequency": "407", "icon": "tourist_archaeological2"},
		"amenity:doctors":              {"label": "Doctors", "frequency": "581", "icon": "health_doctors"},
		"leisure:sports_centre":        {"label": "Sports Centre", "frequency": "767", "icon": "sport_leisure_centre"},
		"leisure:swimming_pool":        {"label": "Swimming Pool", "frequency": "24", "icon": "sport_swimming_outdoor"},
		"shop:supermarket":             {"label": "Supermarket", "frequency": "2673", "icon": "shopping_supermarket"},
		"shop:convenience":             {"label": "Convenience", "frequency": "1469", "icon": "shopping_convenience"},
		"amenity:restaurant":           {"label": "Restaurant", "frequency": "3179", "icon": "food_restaurant"},
		"amenity:fast_food":            {"label": "Fast Food", "frequency": "2289", "icon": "food_fastfood"},
		"amenity:cafe":                 {"label": "Cafe", "frequency": "1780", "icon": "food_cafe"},
		"tourism:guest_house":          {"label": "Guest House", "frequency": "223", "icon": "accommodation_bed_and_breakfast"},
		"amenity:pharmacy":             {"label": "Pharmacy", "frequency": "733", "icon": "health_pharmacy_dispensing"},
		"amenity:fuel":                 {"label": "Fuel", "frequency": "1308", "icon": "transport_fuel"},
		"natural:peak":                 {"label": "Peak", "frequency": "3212", "icon": "poi_peak"},
		"waterway:waterfall":           {"label": "Waterfall", "frequency": "24", "icon": ""},
		"natural:wood":                 {"label": "Wood", "frequency": "1845", "icon": "landuse_coniferous_and_deciduous"},
		"natural:water":                {"label": "Water", "frequency": "1790", "icon": ""},
		"landuse:forest":               {"label": "Forest", "frequency": "467", "icon": ""},
		"landuse:cemetery":             {"label": "Cemetery", "frequency": "463", "icon": ""},
		"landuse:allotments":           {"label": "Allotments", "frequency": "408", "icon": ""},
		"landuse:farmyard":             {"label": "Farmyard", "frequency": "397", "icon": ""},
		"railway:rail":                 {"label": "Rail", "frequency": "4894", "icon": ""},
		"waterway:canal":               {"label": "Canal", "frequency": "1723", "icon": ""},
		"waterway:river":               {"label": "River", "frequency": "4089", "icon": ""},
		"waterway:stream":              {"label": "Stream", "frequency": "2684", "icon": ""},
		"shop:bicycle":                 {"label": "Bicycle", "frequency": "349", "icon": "shopping_bicycle"},
		"shop:clothes":                 {"label": "Clothes", "frequency": "315", "icon": "shopping_clothes"},
		"shop:hairdresser":             {"label": "Hairdresser", "frequency": "312", "icon": "shopping_hairdresser"},
		"shop:doityourself":            {"label": "Doityourself", "frequency": "247", "icon": "shopping_diy"},
		"shop:estate_agent":            {"label": "Estate Agent", "frequency": "162", "icon": "shopping_estateagent2"},
		"shop:car":                     {"label": "Car", "frequency": "159", "icon": "shopping_car"},
		"shop:garden_centre":           {"label": "Garden Centre", "frequency": "143", "icon": "shopping_garden_centre"},
		"shop:car_repair":              {"label": "Car Repair", "frequency": "141", "icon": "shopping_car_repair"},
		"shop:newsagent":               {"label": "Newsagent", "frequency": "132", "icon": ""},
		"shop:bakery":                  {"label": "Bakery", "frequency": "129", "icon": "shopping_bakery"},
		"shop:furniture":               {"label": "Furniture", "frequency": "124", "icon": ""},
		"shop:butcher":                 {"label": "Butcher", "frequency": "105", "icon": "shopping_butcher"},
		"shop:apparel":                 {"label": "Apparel", "frequency": "98", "icon": "shopping_clothes"},
		"shop:electronics":             {"label": "Electronics", "frequency": "96", "icon": ""},
		"shop:department_store":        {"label": "Department Store", "frequency": "86", "icon": ""},
		"shop:books":                   {"label": "Books", "frequency": "85", "icon": ""},
		"shop:yes":                     {"label": "Yes", "frequency": "68", "icon": ""},
		"shop:outdoor":                 {"label": "Outdoor", "frequency": "67", "icon": ""},
		"shop:mall":                    {"label": "Mall", "frequency": "63", "icon": ""},
		"shop:florist":                 {"label": "Florist", "frequency": "61", "icon": ""},
		"shop:charity":                 {"label": "Charity", "frequency": "60", "icon": ""},
		"shop:hardware":                {"label": "Hardware", "frequency": "59", "icon": ""},
		"shop:laundry":                 {"label": "Laundry", "frequency": "51", "icon": "shopping_laundrette"},
		"shop:shoes":                   {"label": "Shoes", "frequency": "49", "icon": ""},
		"shop:beverages":               {"label": "Beverages", "frequency": "48", "icon": "shopping_alcohol"},
		"shop:dry_cleaning":            {"label": "Dry Cleaning", "frequency": "46", "icon": ""},
		"shop:carpet":                  {"label": "Carpet", "frequency": "45", "icon": ""},
		"shop:computer":                {"label": "Computer", "frequency": "44", "icon": ""},
		"shop:alcohol":                 {"label": "Alcohol", "frequency": "44", "icon": "shopping_alcohol"},
		"shop:optician":                {"label": "Optician", "frequency": "55", "icon": "health_opticians"},
		"shop:chemist":                 {"label": "Chemist", "frequency": "42", "icon": "health_pharmacy"},
		"shop:gallery":                 {"label": "Gallery", "frequency": "38", "icon": "tourist_art_gallery2"},
		"shop:mobile_phone":            {"label": "Mobile Phone", "frequency": "37", "icon": ""},
		"shop:sports":                  {"label": "Sports", "frequency": "37", "icon": ""},
		"shop:jewelry":                 {"label": "Jewelry", "frequency": "32", "icon": "shopping_jewelry"},
		"shop:pet":                     {"label": "Pet", "frequency": "29", "icon": ""},
		"shop:beauty":                  {"label": "Beauty", "frequency": "28", "icon": ""},
		"shop:stationery":              {"label": "Stationery", "frequency": "25", "icon": ""},
		"shop:shopping_centre":         {"label": "Shopping Centre", "frequency": "25", "icon": ""},
		"shop:general":                 {"label": "General", "frequency": "25", "icon": ""},
		"shop:electrical":              {"label": "Electrical", "frequency": "25", "icon": ""},
		"shop:toys":                    {"label": "Toys", "frequency": "23", "icon": ""},
		"shop:jeweller":                {"label": "Jeweller", "frequency": "23", "icon": ""},
		"shop:betting":                 {"label": "Betting", "frequency": "23", "icon": ""},
		"shop:household":               {"label": "Household", "frequency": "21", "icon": ""},
		"shop:travel_agency":           {"label": "Travel Agency", "frequency": "21", "icon": ""},
		"shop:hifi":                    {"label": "Hifi", "frequency": "21", "icon": ""},
		"amenity:shop":                 {"label": "Shop", "frequency": "61", "icon": ""},
		"place:house":                  {"label": "House", "frequency": "2086", "icon": "", "defzoom": "18"},
		"place:house_name":             {"label": "House", "frequency": "2086", "icon": "", "defzoom": "18"},
		"place:house_number":           {"label": "House Number", "frequency": "2086", "icon": "", "defzoom": "18"},
		"place:country_code":           {"label": "Country Code", "frequency": "2086", "icon": "", "defzoom": "18"},
		"leisure:pitch":                {"label": "Pitch", "frequency": "762", "icon": ""},
		"highway:unsurfaced":           {"label": "Unsurfaced", "frequency": "492", "icon": ""},
		"historic:ruins":               {"label": "Ruins", "frequency": "483", "icon": "tourist_ruin"},
		"amenity:college":              {"label": "College", "frequency": "473", "icon": "education_school"},
		"historic:monument":            {"label": "Monument", "frequency": "470", "icon": "tourist_monument"},
		"railway:subway":               {"label": "Subway", "frequency": "385", "icon": ""},
		"historic:memorial":            {"label": "Memorial", "frequency": "382", "icon": "tourist_monument"},
		"leisure:nature_reserve":       {"label": "Nature Reserve", "frequency": "342", "icon": ""},
		"leisure:common":               {"label": "Common", "frequency": "322", "icon": ""},
		"waterway:lock_gate":           {"label": "Lock Gate", "frequency": "321", "icon": ""},
		"natural:fell":                 {"label": "Fell", "frequency": "308", "icon": ""},
		"amenity:nightclub":            {"label": "Nightclub", "frequency": "292", "icon": ""},
		"highway:path":                 {"label": "Path", "frequency": "287", "icon": ""},
		"leisure:garden":               {"label": "Garden", "frequency": "285", "icon": ""},
		"landuse:reservoir":            {"label": "Reservoir", "frequency": "276", "icon": ""},
		"leisure:playground":           {"label": "Playground", "frequency": "264", "icon": ""},
		"leisure:stadium":              {"label": "Stadium", "frequency": "212", "icon": ""},
		"historic:mine":                {"label": "Mine", "frequency": "193", "icon": "poi_mine"},
		"natural:cliff":                {"label": "Cliff", "frequency": "193", "icon": ""},
		"tourism:caravan_site":         {"label": "Caravan Site", "frequency": "183", "icon": "accommodation_caravan_park"},
		"amenity:bus_station":          {"label": "Bus Station", "frequency": "181", "icon": "transport_bus_station"},
		"amenity:kindergarten":         {"label": "Kindergarten", "frequency": "179", "icon": ""},
		"highway:construction":         {"label": "Construction", "frequency": "176", "icon": ""},
		"amenity:atm":                  {"label": "Atm", "frequency": "172", "icon": "money_atm2"},
		"amenity:emergency_phone":      {"label": "Emergency Phone", "frequency": "164", "icon": ""},
		"waterway:lock":                {"label": "Lock", "frequency": "146", "icon": ""},
		"waterway:riverbank":           {"label": "Riverbank", "frequency": "143", "icon": ""},
		"natural:coastline":            {"label": "Coastline", "frequency": "142", "icon": ""},
		"tourism:viewpoint":            {"label": "Viewpoint", "frequency": "140", "icon": "tourist_view_point"},
		"tourism:hostel":               {"label": "Hostel", "frequency": "140", "icon": ""},
		"tourism:bed_and_breakfast":    {"label": "Bed And Breakfast", "frequency": "140", "icon": "accommodation_bed_and_breakfast"},
		"railway:halt":                 {"label": "Halt", "frequency": "135", "icon": ""},
		"railway:platform":             {"label": "Platform", "frequency": "134", "icon": ""},
		"railway:tram":                 {"label": "Tram", "frequency": "130", "icon": "transport_tram_stop"},
		"amenity:courthouse":           {"label": "Courthouse", "frequency": "129", "icon": "amenity_court"},
		"amenity:recycling":            {"label": "Recycling", "frequency": "126", "icon": "amenity_recycling"},
		"amenity:dentist":              {"label": "Dentist", "frequency": "124", "icon": "health_dentist"},
		"natural:beach":                {"label": "Beach", "frequency": "121", "icon": "tourist_beach"},
		"place:moor":                   {"label": "Moor", "frequency": "118", "icon": ""},
		"amenity:grave_yard":           {"label": "Grave Yard", "frequency": "110", "icon": ""},
		"waterway:derelict_canal":      {"label": "Derelict Canal", "frequency": "109", "icon": ""},
		"waterway:drain":               {"label": "Drain", "frequency": "108", "icon": ""},
		"landuse:grass":                {"label": "Grass", "frequency": "106", "icon": ""},
		"landuse:village_green":        {"label": "Village Green", "frequency": "106", "icon": ""},
		"natural:bay":                  {"label": "Bay", "frequency": "102", "icon": ""},
		"railway:tram_stop":            {"label": "Tram Stop", "frequency": "101", "icon": "transport_tram_stop"},
		"leisure:marina":               {"label": "Marina", "frequency": "98", "icon": ""},
		"highway:stile":                {"label": "Stile", "frequency": "97", "icon": ""},
		"natural:moor":                 {"label": "Moor", "frequency": "95", "icon": ""},
		"railway:light_rail":           {"label": "Light Rail", "frequency": "91", "icon": ""},
		"railway:narrow_gauge":         {"label": "Narrow Gauge", "frequency": "90", "icon": ""},
		"natural:land":                 {"label": "Land", "frequency": "86", "icon": ""},
		"amenity:village_hall":         {"label": "Village Hall", "frequency": "82", "icon": ""},
		"waterway:dock":                {"label": "Dock", "frequency": "80", "icon": ""},
		"amenity:veterinary":           {"label": "Veterinary", "frequency": "79", "icon": ""},
		"landuse:brownfield":           {"label": "Brownfield", "frequency": "77", "icon": ""},
		"leisure:track":                {"label": "Track", "frequency": "76", "icon": ""},
		"railway:historic_station":     {"label": "Historic Station", "frequency": "74", "icon": ""},
		"landuse:construction":         {"label": "Construction", "frequency": "72", "icon": ""},
		"amenity:prison":               {"label": "Prison", "frequency": "71", "icon": "amenity_prison"},
		"landuse:quarry":               {"label": "Quarry", "frequency": "71", "icon": ""},
		"amenity:telephone":            {"label": "Telephone", "frequency": "70", "icon": ""},
		"highway:traffic_signals":      {"label": "Traffic Signals", "frequency": "66", "icon": ""},
		"natural:heath":                {"label": "Heath", "frequency": "62", "icon": ""},
		"historic:house":               {"label": "House", "frequency": "61", "icon": ""},
		"amenity:social_club":          {"label": "Social Club", "frequency": "61", "icon": ""},
		"landuse:military":             {"label": "Military", "frequency": "61", "icon": ""},
		"amenity:health_centre":        {"label": "Health Centre", "frequency": "59", "icon": ""},
		"historic:building":            {"label": "Building", "frequency": "58", "icon": ""},
		"amenity:clinic":               {"label": "Clinic", "frequency": "57", "icon": ""},
		"highway:services":             {"label": "Services", "frequency": "56", "icon": ""},
		"amenity:ferry_terminal":       {"label": "Ferry Terminal", "frequency": "55", "icon": ""},
		"natural:marsh":                {"label": "Marsh", "frequency": "55", "icon": ""},
		"natural:hill":                 {"label": "Hill", "frequency": "54", "icon": ""},
		"highway:raceway":              {"label": "Raceway", "frequency": "53", "icon": ""},
		"amenity:taxi":                 {"label": "Taxi", "frequency": "47", "icon": ""},
		"amenity:take_away":            {"label": "Take Away", "frequency": "45", "icon": ""},
		"amenity:car_rental":           {"label": "Car Rental", "frequency": "44", "icon": ""},
		"place:islet":                  {"label": "Islet", "frequency": "44", "icon": ""},
		"amenity:nursery":              {"label": "Nursery", "frequency": "44", "icon": ""},
		"amenity:nursing_home":         {"label": "Nursing Home", "frequency": "43", "icon": ""},
		"amenity:toilets":              {"label": "Toilets", "frequency": "38", "icon": ""},
		"amenity:hall":                 {"label": "Hall", "frequency": "38", "icon": ""},
		"waterway:boatyard":            {"label": "Boatyard", "frequency": "36", "icon": ""},
		"highway:mini_roundabout":      {"label": "Mini Roundabout", "frequency": "35", "icon": ""},
		"historic:manor":               {"label": "Manor", "frequency": "35", "icon": ""},
		"tourism:chalet":               {"label": "Chalet", "frequency": "34", "icon": ""},
		"amenity:bicycle_parking":      {"label": "Bicycle Parking", "frequency": "34", "icon": ""},
		"amenity:hotel":                {"label": "Hotel", "frequency": "34", "icon": ""},
		"waterway:weir":                {"label": "Weir", "frequency": "33", "icon": ""},
		"natural:wetland":              {"label": "Wetland", "frequency": "33", "icon": ""},
		"natural:cave_entrance":        {"label": "Cave Entrance", "frequency": "32", "icon": ""},
		"amenity:crematorium":          {"label": "Crematorium", "frequency": "31", "icon": ""},
		"tourism:picnic_site":          {"label": "Picnic Site", "frequency": "31", "icon": ""},
		"landuse:wood":                 {"label": "Wood", "frequency": "30", "icon": ""},
		"landuse:basin":                {"label": "Basin", "frequency": "30", "icon": ""},
		"natural:tree":                 {"label": "Tree", "frequency": "30", "icon": ""},
		"leisure:slipway":              {"label": "Slipway", "frequency": "29", "icon": ""},
		"landuse:meadow":               {"label": "Meadow", "frequency": "29", "icon": ""},
		"landuse:piste":                {"label": "Piste", "frequency": "28", "icon": ""},
		"amenity:care_home":            {"label": "Care Home", "frequency": "28", "icon": ""},
		"amenity:club":                 {"label": "Club", "frequency": "28", "icon": ""},
		"amenity:medical_centre":       {"label": "Medical Centre", "frequency": "27", "icon": ""},
		"historic:roman_road":          {"label": "Roman Road", "frequency": "27", "icon": ""},
		"historic:fort":                {"label": "Fort", "frequency": "26", "icon": ""},
		"railway:subway_entrance":      {"label": "Subway Entrance", "frequency": "26", "icon": ""},
		"historic:yes":                 {"label": "Yes", "frequency": "25", "icon": ""},
		"highway:gate":                 {"label": "Gate", "frequency": "25", "icon": ""},
		"leisure:fishing":              {"label": "Fishing", "frequency": "24", "icon": ""},
		"historic:museum":              {"label": "Museum", "frequency": "24", "icon": ""},
		"amenity:car_wash":             {"label": "Car Wash", "frequency": "24", "icon": ""},
		"railway:level_crossing":       {"label": "Level Crossing", "frequency": "23", "icon": ""},
		"leisure:bird_hide":            {"label": "Bird Hide", "frequency": "23", "icon": ""},
		"natural:headland":             {"label": "Headland", "frequency": "21", "icon": ""},
		"tourism:apartments":           {"label": "Apartments", "frequency": "21", "icon": ""},
		"amenity:shopping":             {"label": "Shopping", "frequency": "21", "icon": ""},
		"natural:scrub":                {"label": "Scrub", "frequency": "20", "icon": ""},
		"natural:fen":                  {"label": "Fen", "frequency": "20", "icon": ""},
		"building:yes":                 {"label": "Building", "frequency": "200", "icon": ""},
		"mountain_pass:yes":            {"label": "Mountain Pass", "frequency": "200", "icon": ""},
		"amenity:parking":              {"label": "Parking", "frequency": "3157", "icon": ""},
		"highway:bus_stop":             {"label": "Bus Stop", "frequency": "35777", "icon": "transport_bus_stop2"},
		"place:postcode":               {"label": "Postcode", "frequency": "27267", "icon": ""},
		"amenity:post_box":             {"label": "Post Box", "frequency": "9613", "icon": ""},
		"place:houses":                 {"label": "Houses", "frequency": "85", "icon": ""},
		"railway:preserved":            {"label": "Preserved", "frequency": "227", "icon": ""},
		"waterway:derelict canal":      {"label": "Derelict Canal", "frequency": "21", "icon": ""},
		"amenity:dead_pub":             {"label": "Dead Pub", "frequency": "20", "icon": ""},
		"railway:disused_station":      {"label": "Disused Station", "frequency": "114", "icon": ""},
		"railway:abandoned":            {"label": "Abandoned", "frequency": "641", "icon": ""},
		"railway:disused":              {"label": "Disused", "frequency": "72", "icon": ""},
	}
	//return m

	/*for key, word := range m {
		fmt.Print(key, ":")
		for keyIn, wordIn := range word {
			fmt.Print(keyIn, ":", wordIn)
		}
		fmt.Println()
	}*/
}
